--Empreendimentos mais acessados em Caxias do sul

SELECT COUNT(EA.EMPREENDIMENTO_ID) AS ACESSO,
	E.ID AS EMPREENDIMENTO,
	C.NOME
FROM PUBLIC.EMPREENDIMENTO E
RIGHT OUTER JOIN PUBLIC.EMPREENDIMENTO_ACESSOS EA ON EA.EMPREENDIMENTO_ID = E.ID
JOIN PUBLIC.CIDADE C ON C.ID = E.CIDADE_ID
GROUP BY E.ID,
	C.NOME
HAVING C.NOME IN ('Caxias do Sul')
ORDER BY ACESSO DESC;