/*CREATE INDEX CRIADOAPOS2019 ON USERS (CREATED_AT)
WHERE EXTRACT(YEAR FROM CREATED_AT) > 2019
*/
EXPLAIN SELECT C.ID,
	U.ID,
	C.CREATED_AT,
	U.CREATED_AT
FROM CORRETOR C
JOIN USERS U ON U.ID = C.USER_ID
WHERE extract (year from U.CREATED_AT) > 2019