--Valida os empreendimentos que possuem 1 ou mais plantas, suas localizacoes e sua posicao solar

SELECT E.ID AS EMPREENDIMENTO,
	EP.ID AS PLANTA,
	EPS.POSICAO AS POSICAO_SOLAR,
	B.NOME AS BAIRRO,
	C.NOME AS CIDADE,
	ES.UF
FROM EMPREENDIMENTO_PLANTA EP
FULL JOIN EMPREENDIMENTO_PLANTA_POSICAO_SOLAR EPS ON EPS.EMPREENDIMENTO_PLANTA_ID = EP.ID
FULL JOIN EMPREENDIMENTO E ON E.ID = EP.EMPREENDIMENTO_ID
FULL JOIN CIDADE C ON C.ID = E.CIDADE_ID
FULL JOIN BAIRRO B ON B.ID = E.BAIRRO_ID
FULL JOIN ESTADO ES ON ES.ID = C.ESTADO_ID
WHERE /*NOT*/ EXISTS
		(SELECT EPS.EMPREENDIMENTO_PLANTA_ID
			FROM EMPREENDIMENTO_PLANTA_POSICAO_SOLAR
			WHERE EPS.EMPREENDIMENTO_PLANTA_ID = EP.ID)
GROUP BY ES.UF,
	C.NOME,
	B.NOME,
	E.ID,
	EP.ID,
	EPS.ID
ORDER BY ES.UF,
	C.NOME ASC